import { FacebookAuthProvider, signInWithPopup } from "firebase/auth";
import Head from "next/head";
import { auth } from "../utils/firebase/firebaseClient";
import { trpc } from "../utils/trpc";
import { useAuth } from "../context/auth";
import { mongo } from "mongoose";

export default function Home() {
  async function handleLogin() {
    const provider = new FacebookAuthProvider();
    const result = await signInWithPopup(auth, provider);
    const user = result.user;

    fetch("/api/users", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(user),
    });
  }

  const { user } = useAuth();
  console.log("useAuth", user);

  // const listPosts = trpc.post.list.useQuery();
  // console.log(listPosts.data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={handleLogin}>Login</button>
        </div>
      </main>
    </>
  );
}
