import { FacebookAuthProvider, signInWithPopup } from "firebase/auth";
import Head from "next/head";
import { auth } from "../utils/firebase/firebaseClient";
import { useEffect } from "react";
import { trpc } from "../utils/trpc";

export default function Home() {
  async function handleLogin() {
    const provider = new FacebookAuthProvider();
    const result = await signInWithPopup(auth, provider);
    const user = result.user;
  }

  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      console.log(user);
    });
    return unsubscribe;
  }, []);

  const listPosts = trpc.post.list.useQuery();
  console.log(listPosts.data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={handleLogin}>Login</button>
        </div>
      </main>
    </>
  );
}
