import React from "react";

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="container mx-auto p-6">
      <h1 className="text-3xl font-bold">Privacy Policy</h1>
      <p className="text-gray-600">Last updated: February 25, 2025</p>
      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the{" "}
        <a
          href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-500 underline"
        >
          Free Privacy Policy Generator
        </a>
        .
      </p>

      <h2 className="text-2xl font-semibold mt-4">
        Interpretation and Definitions
      </h2>
      <h3 className="text-xl font-semibold mt-3">Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-xl font-semibold mt-3">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-6">
        <li>
          <strong>Account:</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate:</strong> means an entity that controls, is
          controlled by, or is under common control with a party, where
          &quot;control&quot; means ownership of 50% or more of the shares, equity
          interest, or other securities entitled to vote for election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company:</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;,
          &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Angels Among Us, PO Box
          821, Alpharetta, GA 30009.
        </li>
        <li>
          <strong>Cookies:</strong> are small files that are placed on Your
          computer, mobile device, or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country:</strong> refers to: Georgia, United States.
        </li>
        <li>
          <strong>Device:</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data:</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service:</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider:</strong> means any natural or legal person
          who processes the data on behalf of the Company.
        </li>
        <li>
          <strong>Third-party Social Media Service:</strong> refers to any
          website or social network website through which a User can log in or
          create an account to use the Service.
        </li>
        <li>
          <strong>Usage Data:</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself.
        </li>
        <li>
          <strong>Website:</strong> refers to Angels Among Us, accessible from{" "}
          <a
            href="https://fosters.angelsrescue.org/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-500 underline"
          >
            https://fosters.angelsrescue.org/
          </a>
          .
        </li>
        <li>
          <strong>You:</strong> means the individual accessing or using the
          Service, or the company or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-4">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-xl font-semibold mt-3">Types of Data Collected</h3>
      <h4 className="text-lg font-semibold mt-3">Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc pl-6">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold mt-3">Usage Data</h4>
      <p>
        Usage Data is collected automatically when using the Service and may
        include information such as Your Device&apos;s IP address, browser type,
        browser version, pages visited, time spent on pages, and other
        diagnostic data.
      </p>

      <h4 className="text-lg font-semibold mt-3">
        Information from Third-Party Social Media Services
      </h4>
      <p>
        The Company allows You to create an account and log in using services
        such as:
      </p>
      <ul className="list-disc pl-6">
        <li>Google</li>
        <li>Facebook</li>
        <li>Instagram</li>
        <li>Twitter</li>
        <li>LinkedIn</li>
      </ul>
      <p>
        If You register through a Third-Party Social Media Service, We may
        collect Personal Data associated with that account.
      </p>

      <h4 className="text-lg font-semibold mt-3">
        Tracking Technologies and Cookies
      </h4>
      <p>
        We use Cookies and similar tracking technologies to track activity on
        Our Service and store certain information.
      </p>
      <ul className="list-disc pl-6">
        <li>
          <strong>Cookies:</strong> Small files placed on Your Device.
        </li>
        <li>
          <strong>Web Beacons:</strong> Small electronic files that track users
          visiting pages or opening emails.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mt-3">Contact Us</h3>
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc pl-6">
        <li>
          By email:{" "}
          <a
            href="mailto:gt.engineering@hack4impact.org"
            className="text-blue-500 underline"
          >
            gt.engineering@hack4impact.org
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
